import antfu from "@antfu/eslint-config";

export default antfu({
  type: "lib",
  stylistic: false,
  markdown: false,
  typescript: {
    tsconfigPath: "tsconfig.json",
    overrides: {
      "ts/array-type": ["error", { default: "generic" }],
      "ts/await-thenable": "error",
      "ts/consistent-indexed-object-style": ["error", "record"],
      "ts/consistent-type-definitions": ["error", "type"],
      "ts/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "ts/non-nullable-type-assertion-style": "error",
      "ts/no-array-delete": "error",
      "ts/no-dynamic-delete": "error",
      "ts/no-deprecated": ["error"],
      "ts/no-duplicate-type-constituents": "error",
      "ts/no-explicit-any": "error",
      "ts/no-inferrable-types": "error",
      "ts/no-redundant-type-constituents": "error",
      "ts/no-unnecessary-boolean-literal-compare": "error",
      "ts/no-unnecessary-condition": "error",
      "ts/no-unsafe-argument": "error",
      "ts/no-unsafe-assignment": "error",
      "ts/no-unsafe-call": "error",
      "ts/no-unsafe-member-access": "error",
      "ts/no-unsafe-return": "error",
      "ts/no-unused-vars": "off",
      "ts/prefer-includes": "warn",
      "ts/prefer-nullish-coalescing": "error",
      "ts/prefer-optional-chain": "warn",
      "ts/prefer-regexp-exec": "error",
      "ts/prefer-string-starts-ends-with": "error",
      "ts/restrict-plus-operands": "error",
      "ts/switch-exhaustiveness-check": [
        "warn",
        { considerDefaultExhaustiveForUnions: true },
      ],
      "ts/use-unknown-in-catch-callback-variable": "error",
    },
  },
  unicorn: {
    allRecommended: true,
    overrides: {
      "unicorn/better-regex": "error",
      "unicorn/filename-case": [
        "error",
        { case: "kebabCase", ignore: ["README.md", "CHANGELOG.md", "LICENSE"] },
      ],
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-null": "off",
      "unicorn/no-negated-condition": "off",
      "unicorn/no-thenable": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/prefer-ternary": "off",
    },
  },
  imports: {
    overrides: {
      "perfectionist/sort-imports": [
        "error",
        {
          tsconfig: { rootDir: import.meta.dirname, filename: "tsconfig.json" },
          internalPattern: ["#/*"],
          newlinesBetween: 0,
          order: "asc",
          type: "natural",
        },
      ],
    },
  },
  rules: {
    "antfu/no-top-level-await": ["off"],
    "jsonc/sort-keys": "off",
    "no-console": ["error"],
    "no-restricted-imports": ["error", { patterns: ["..*"] }],
    "pnpm/json-enforce-catalog": "off",
    "pnpm/yaml-enforce-settings": "off",
  },
});
